# Generated by Django 5.1.3 on 2024-11-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_remove_userprofile_user_dossier_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
