# Generated by Django 5.1.3 on 2024-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_dossier_is_favorite_alter_document_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
